backend:
  name: test-repo
  repo: kre1z0/ggwp
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "articles"
    label: "Статьи"
    widget: "string"
    folder: "src/data/articles"
    identifier_field: "name"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article"}
      - {label: "Заголовок статьи", name: "title", widget: "string"}
      - {label: "Краткое описание статьи", name: "description", widget: "text"}
      - {label: "Изображение для предосмотра", name: "preview", widget: "image"}
      - {label: "Теги", name: "tags", widget: "list"}
      - {label: "Дата публикации статьи", name: "date", widget: "date", default: ""}
      - {label: "Статья", name: "body", widget: "markdown"}
  - name: "counties"
    label: "Страны"
    widget: "string"
    folder: "src/data/counties"
    identifier_field: "name"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "counties"}
      - {label: "Страна", name: "country", widget: "country-select", default: "Украина"}
      - label: "Поля"
        name: "fields"
        widget: "list"
        required: false
        default: [null]
        fields:
          - {label: "Имя", name: "name", widget: "string", default: ""}
          - {label: "Значение", name: "value", widget: "string", default: ""}
